Repository microsoft/testfx, pull requests merged in 2024-11, with the labels that each got.

#4012 Only ship TestAdapter related resources
  eng/verify-nupkgs.ps1
  src/Adapter/MSTest.TestAdapter/MSTest.TestAdapter.nuspec
Labels: Type: Bug

#4015 Add TestData property to the TestContext
  src/Adapter/MSTest.TestAdapter/Execution/TestMethodRunner.cs
  src/Adapter/MSTestAdapter.PlatformServices/Interfaces/ITestContext.cs
  src/Adapter/MSTestAdapter.PlatformServices/PublicAPI/PublicAPI.Unshipped.txt
  src/Adapter/MSTestAdapter.PlatformServices/Services/TestContextImplementation.cs
  src/TestFramework/TestFramework.Extensions/PublicAPI/PublicAPI.Unshipped.txt
  src/TestFramework/TestFramework.Extensions/TestContext.cs
  test/IntegrationTests/MSTest.Acceptance.IntegrationTests/TestContextTests.cs
Labels: Type: Feature

#4018 Add TestException property to the TestContext
  src/Adapter/MSTest.TestAdapter/Execution/TestMethodInfo.cs
  src/Adapter/MSTestAdapter.PlatformServices/Interfaces/ITestContext.cs
  src/Adapter/MSTestAdapter.PlatformServices/PublicAPI/PublicAPI.Unshipped.txt
  src/Adapter/MSTestAdapter.PlatformServices/Services/TestContextImplementation.cs
  src/TestFramework/TestFramework.Extensions/PublicAPI/PublicAPI.Unshipped.txt
  src/TestFramework/TestFramework.Extensions/TestContext.cs
  test/IntegrationTests/MSTest.Acceptance.IntegrationTests/TestContextTests.cs
Labels: Type: Feature

#3827 Add code fix for MSTEST0021
  Directory.Packages.props
  src/Analyzers/MSTest.Analyzers.CodeFixes/CodeFixResources.Designer.cs
  src/Analyzers/MSTest.Analyzers.CodeFixes/CodeFixResources.resx
  src/Analyzers/MSTest.Analyzers.CodeFixes/PreferDisposeOverTestCleanupFixer.cs
  src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.cs.xlf
  src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.de.xlf
  src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.es.xlf
  src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.fr.xlf
  src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.it.xlf
  src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.ja.xlf
  src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.ko.xlf
  src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.pl.xlf
  src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.pt-BR.xlf
  src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.ru.xlf
  src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.tr.xlf
  src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.zh-Hans.xlf
  src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.zh-Hant.xlf
  src/Analyzers/MSTest.Analyzers/Helpers/WellKnownTypeNames.cs
  test/UnitTests/MSTest.Analyzers.UnitTests/MSTest.Analyzers.UnitTests.csproj
  test/UnitTests/MSTest.Analyzers.UnitTests/PreferDisposeOverTestCleanupAnalyzerTests.cs
Labels: Type: Feature, Area: Analyzers

#4037 Add TestDisplayName property to the TestContext
  src/Adapter/MSTest.TestAdapter/Execution/TestMethodRunner.cs
  src/Adapter/MSTestAdapter.PlatformServices/Interfaces/ITestContext.cs
  src/Adapter/MSTestAdapter.PlatformServices/PublicAPI/PublicAPI.Unshipped.txt
  src/Adapter/MSTestAdapter.PlatformServices/Services/TestContextImplementation.cs
  src/TestFramework/TestFramework.Extensions/PublicAPI/PublicAPI.Unshipped.txt
  src/TestFramework/TestFramework.Extensions/TestContext.cs
  test/IntegrationTests/MSTest.Acceptance.IntegrationTests/TestContextTests.cs
Labels: Type: Feature

#4038 Implement codefix for MSTEST0006 (AvoidExpectedException)
  src/Analyzers/MSTest.Analyzers.CodeFixes/AvoidExpectedExceptionAttributeFixer.cs
  src/Analyzers/MSTest.Analyzers.CodeFixes/CodeFixResources.Designer.cs
  src/Analyzers/MSTest.Analyzers.CodeFixes/CodeFixResources.resx
  src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.cs.xlf
  src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.de.xlf
  src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.es.xlf
  src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.fr.xlf
  src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.it.xlf
  src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.ja.xlf
  src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.ko.xlf
  src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.pl.xlf
  src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.pt-BR.xlf
  src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.ru.xlf
  src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.tr.xlf
  src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.zh-Hans.xlf
  src/Analyzers/MSTest.Analyzers.CodeFixes/xlf/CodeFixResources.zh-Hant.xlf
  src/Analyzers/MSTest.Analyzers/AvoidExpectedExceptionAttributeAnalyzer.cs
  test/UnitTests/MSTest.Analyzers.UnitTests/AvoidExpectedExceptionAttributeAnalyzerTests.cs
Labels: Type: Feature, Area: Analyzers

#4041 Add key only overload to TestMetadataProperty
  src/Platform/Microsoft.Testing.Platform/Messages/TestNodeProperties.cs
  src/Platform/Microsoft.Testing.Platform/PublicAPI/PublicAPI.Unshipped.txt
Labels: Area: Testing Platform

#4045 Respect custom ExpectedExceptionBase attribute implementations
  src/Analyzers/MSTest.Analyzers/AvoidExpectedExceptionAttributeAnalyzer.cs
  src/Analyzers/MSTest.Analyzers/Helpers/WellKnownTypeNames.cs
  src/Analyzers/MSTest.Analyzers/UseAttributeOnTestMethodAnalyzer.cs
  test/UnitTests/MSTest.Analyzers.UnitTests/AvoidExpectedExceptionAttributeAnalyzerTests.cs
  test/UnitTests/MSTest.Analyzers.UnitTests/UseAttributeOnTestMethodAnalyzerTests.cs
Labels: Type: Bug, Area: Analyzers

#4058 Fix DataSourceAttribute not being discovered with TestDataSourceDiscoveryOption.DuringDiscovery
  azure-pipelines.yml
  eng/install-access-database-engine.ps1
  src/Adapter/MSTest.TestAdapter/Discovery/AssemblyEnumerator.cs
  test/IntegrationTests/MSTest.Acceptance.IntegrationTests/DataSourceTests.cs
Labels: Type: Bug, Type: Regression

#4057 Refactor unnecessary try/catch
  src/Adapter/MSTest.TestAdapter/Discovery/AssemblyEnumerator.cs
  src/Adapter/MSTest.TestAdapter/DynamicDataOperations.cs
  src/Adapter/MSTest.TestAdapter/Execution/TestMethodRunner.cs
  src/TestFramework/TestFramework/Attributes/DataSource/DynamicDataAttribute.cs
  src/TestFramework/TestFramework/Interfaces/EmptyDataSourceExceptionInfoExtensions.cs
  src/TestFramework/TestFramework/Interfaces/ITestDataSourceEmptyDataSourceExceptionInfo.cs
  test/UnitTests/MSTestAdapter.UnitTests/DynamicDataAttributeTests.cs
  test/UnitTests/MSTestAdapter.UnitTests/Execution/TestMethodRunnerTests.cs
  test/UnitTests/MSTestAdapter.UnitTests/TestableImplementations/TestablePlatformServiceProvider.cs
Labels: Area: Performance

#4053 Consider readonly TestContext as valid
  src/Adapter/MSTest.TestAdapter/Discovery/TypeValidator.cs
  src/Adapter/MSTest.TestAdapter/Resources/Resource.Designer.cs
  src/Adapter/MSTest.TestAdapter/Resources/Resource.resx
  src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.cs.xlf
  src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.de.xlf
  src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.es.xlf
  src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.fr.xlf
  src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.it.xlf
  src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.ja.xlf
  src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.ko.xlf
  src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.pl.xlf
  src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.pt-BR.xlf
  src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.ru.xlf
  src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.tr.xlf
  src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.zh-Hans.xlf
  src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.zh-Hant.xlf
  src/Analyzers/MSTest.Analyzers.CodeFixes/TestContextShouldBeValidFixer.cs
  src/Analyzers/MSTest.Analyzers/Resources.Designer.cs
  src/Analyzers/MSTest.Analyzers/Resources.resx
  src/Analyzers/MSTest.Analyzers/TestContextShouldBeValidAnalyzer.cs
  src/Analyzers/MSTest.Analyzers/xlf/Resources.cs.xlf
  src/Analyzers/MSTest.Analyzers/xlf/Resources.de.xlf
  src/Analyzers/MSTest.Analyzers/xlf/Resources.es.xlf
  src/Analyzers/MSTest.Analyzers/xlf/Resources.fr.xlf
  src/Analyzers/MSTest.Analyzers/xlf/Resources.it.xlf
  src/Analyzers/MSTest.Analyzers/xlf/Resources.ja.xlf
  src/Analyzers/MSTest.Analyzers/xlf/Resources.ko.xlf
  src/Analyzers/MSTest.Analyzers/xlf/Resources.pl.xlf
  src/Analyzers/MSTest.Analyzers/xlf/Resources.pt-BR.xlf
  src/Analyzers/MSTest.Analyzers/xlf/Resources.ru.xlf
  src/Analyzers/MSTest.Analyzers/xlf/Resources.tr.xlf
  src/Analyzers/MSTest.Analyzers/xlf/Resources.zh-Hans.xlf
  src/Analyzers/MSTest.Analyzers/xlf/Resources.zh-Hant.xlf
  test/IntegrationTests/MSTest.Acceptance.IntegrationTests/TestContextTests.cs
  test/UnitTests/MSTest.Analyzers.UnitTests/TestContextShouldBeValidAnalyzerTests.cs
  test/UnitTests/MSTestAdapter.UnitTests/Discovery/TypeValidatorTests.cs
Labels: Type: Bug

#4072 Support rsp in MTP
  src/Platform/Microsoft.Testing.Platform/CommandLine/ParseResult.cs
  src/Platform/Microsoft.Testing.Platform/CommandLine/Parser.cs
  src/Platform/Microsoft.Testing.Platform/CommandLine/ResponseFileHelper.cs
  src/Platform/Microsoft.Testing.Platform/Resources/PlatformResources.resx
  src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.cs.xlf
  src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.de.xlf
  src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.es.xlf
  src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.fr.xlf
  src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.it.xlf
  src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.ja.xlf
  src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.ko.xlf
  src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.pl.xlf
  src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.pt-BR.xlf
  src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.ru.xlf
  src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.tr.xlf
  src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.zh-Hans.xlf
  src/Platform/Microsoft.Testing.Platform/Resources/xlf/PlatformResources.zh-Hant.xlf
  test/UnitTests/Microsoft.Testing.Platform.UnitTests/CommandLine/CommandLineHandlerTests.cs
  test/UnitTests/Microsoft.Testing.Platform.UnitTests/CommandLine/CommandLineTests.cs
  test/UnitTests/Microsoft.Testing.Platform.UnitTests/Configuration/ConfigurationManagerTests.cs
Labels: Type: Discussion, Type: Feature, Area: Testing Platform

#4144 Improve error message for incompatible architecture
  src/Platform/Microsoft.Testing.Platform.MSBuild/Resources/MSBuildResources.resx
  src/Platform/Microsoft.Testing.Platform.MSBuild/Resources/xlf/MSBuildResources.cs.xlf
  src/Platform/Microsoft.Testing.Platform.MSBuild/Resources/xlf/MSBuildResources.de.xlf
  src/Platform/Microsoft.Testing.Platform.MSBuild/Resources/xlf/MSBuildResources.es.xlf
  src/Platform/Microsoft.Testing.Platform.MSBuild/Resources/xlf/MSBuildResources.fr.xlf
  src/Platform/Microsoft.Testing.Platform.MSBuild/Resources/xlf/MSBuildResources.it.xlf
  src/Platform/Microsoft.Testing.Platform.MSBuild/Resources/xlf/MSBuildResources.ja.xlf
  src/Platform/Microsoft.Testing.Platform.MSBuild/Resources/xlf/MSBuildResources.ko.xlf
  src/Platform/Microsoft.Testing.Platform.MSBuild/Resources/xlf/MSBuildResources.pl.xlf
  src/Platform/Microsoft.Testing.Platform.MSBuild/Resources/xlf/MSBuildResources.pt-BR.xlf
  src/Platform/Microsoft.Testing.Platform.MSBuild/Resources/xlf/MSBuildResources.ru.xlf
  src/Platform/Microsoft.Testing.Platform.MSBuild/Resources/xlf/MSBuildResources.tr.xlf
  src/Platform/Microsoft.Testing.Platform.MSBuild/Resources/xlf/MSBuildResources.zh-Hans.xlf
  src/Platform/Microsoft.Testing.Platform.MSBuild/Resources/xlf/MSBuildResources.zh-Hant.xlf
  src/Platform/Microsoft.Testing.Platform.MSBuild/Tasks/InvokeTestingPlatformTask.cs
  test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/MSBuildTests.Test.cs
Labels: Area: Testing Platform

#4153 Use Polyfill lock
  src/Platform/Microsoft.Testing.Platform/OutputDevice/Terminal/TestProgressStateAwareTerminal.cs
Labels: Area: Performance

#4156 Further `System.Threading.Lock` usages
  src/Platform/Microsoft.Testing.Platform/Extensions/CompositeExtensionsFactory.cs
  src/Platform/Microsoft.Testing.Platform/Hosts/ServerTestHost.cs
Labels: Area: Performance

#4160 Improve Regex to Reduce Matching Time
  src/Platform/Microsoft.Testing.Platform/OutputDevice/Terminal/TerminalTestReporter.cs
  test/UnitTests/Microsoft.Testing.Platform.UnitTests/OutputDevice/Terminal/TerminalTestReporterTests.cs
Labels: Area: Testing Platform, Area: Terminal reporter

#4189 Remove timeout from regex and improve test
  src/Platform/Microsoft.Testing.Platform/OutputDevice/Terminal/TerminalTestReporter.cs
  test/UnitTests/Microsoft.Testing.Platform.UnitTests/OutputDevice/Terminal/TerminalTestReporterTests.cs
Labels: Area: Testing Platform, Area: Terminal reporter
