Repository microsoft/testfx, pull requests merged in 2024-05, with the labels that each got.

#2771 treat missing dynamic data as inconclusive
  src/Adapter/MSTest.TestAdapter/Discovery/AssemblyEnumerator.cs
  src/Adapter/MSTest.TestAdapter/Execution/TestMethodRunner.cs
  src/Adapter/MSTest.TestAdapter/MSTestSettings.cs
  test/IntegrationTests/MSTest.Acceptance.IntegrationTests/DynamicDataTests.cs
  test/IntegrationTests/MSTest.Acceptance.IntegrationTests/testsbaseline.txt
Labels: Type: Feature

#2865 Run and fail tests when ITestDataSource.GetData returns empty IEnumerable
  src/Adapter/MSTest.TestAdapter/Discovery/AssemblyEnumerator.cs
  src/Adapter/MSTest.TestAdapter/Execution/TestMethodRunner.cs
  test/IntegrationTests/MSTest.Acceptance.IntegrationTests/DynamicDataTests.cs
  test/IntegrationTests/MSTest.Acceptance.IntegrationTests/ParameterizedTestTests.cs
  test/IntegrationTests/MSTest.Acceptance.IntegrationTests/testsbaseline.txt
  test/IntegrationTests/MSTest.VstestConsoleWrapper.IntegrationTests/Parameterized tests/DataExtensibilityTests.cs
  test/IntegrationTests/TestAssets/FxExtensibilityTestProject/DynamicDataExMoreTests.cs
  test/IntegrationTests/TestAssets/FxExtensibilityTestProject/DynamicDataExTests.cs
  test/IntegrationTests/TestAssets/FxExtensibilityTestProject/TestDataSourceExTests.cs
Labels: Type: Feature, Area: Data Driven

#2969 simplify GetResolutionPaths
  src/Adapter/MSTestAdapter.PlatformServices/Utilities/AssemblyUtility.cs
Labels: Needs: Author Feedback
