Repository microsoft/testfx, pull requests merged in 2024-07, with the labels that each got.

#3231 Refactor STA pool code
  src/Adapter/MSTest.TestAdapter/Execution/TestExecutionManager.cs
Labels: Area: Performance

#3267 Feature: add support for injecting TestContext in ctor
  src/Adapter/MSTest.TestAdapter/Execution/TestClassInfo.cs
  src/Adapter/MSTest.TestAdapter/Execution/TestMethodInfo.cs
  src/Adapter/MSTest.TestAdapter/Execution/TypeCache.cs
  src/Adapter/MSTest.TestAdapter/Resources/Resource.Designer.cs
  src/Adapter/MSTest.TestAdapter/Resources/Resource.resx
  src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.cs.xlf
  src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.de.xlf
  src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.es.xlf
  src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.fr.xlf
  src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.it.xlf
  src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.ja.xlf
  src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.ko.xlf
  src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.pl.xlf
  src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.pt-BR.xlf
  src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.ru.xlf
  src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.tr.xlf
  src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.zh-Hans.xlf
  src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.zh-Hant.xlf
  test/IntegrationTests/MSTest.Acceptance.IntegrationTests/TestContextTests.cs
  test/UnitTests/MSTestAdapter.UnitTests/Execution/TestClassInfoTests.cs
  test/UnitTests/MSTestAdapter.UnitTests/Execution/TestMethodInfoTests.cs
  test/UnitTests/MSTestAdapter.UnitTests/Execution/TestMethodRunnerTests.cs
  test/UnitTests/MSTestAdapter.UnitTests/Execution/TypeCacheTests.cs
Labels: Type: Feature

#3284 Fix test case id filtering for server mode
  src/Adapter/MSTest.TestAdapter/TestMethodFilter.cs
  src/Platform/Microsoft.Testing.Extensions.VSTestBridge/ObjectModel/ObjectModelConverters.cs
  src/Platform/Microsoft.Testing.Extensions.VSTestBridge/ObjectModel/RunContextAdapter.cs
  src/Platform/Microsoft.Testing.Extensions.VSTestBridge/Resources/ExtensionResources.Designer.cs
  src/Platform/Microsoft.Testing.Extensions.VSTestBridge/Resources/ExtensionResources.resx
  src/Platform/Microsoft.Testing.Extensions.VSTestBridge/Resources/xlf/ExtensionResources.cs.xlf
  src/Platform/Microsoft.Testing.Extensions.VSTestBridge/Resources/xlf/ExtensionResources.de.xlf
  src/Platform/Microsoft.Testing.Extensions.VSTestBridge/Resources/xlf/ExtensionResources.es.xlf
  src/Platform/Microsoft.Testing.Extensions.VSTestBridge/Resources/xlf/ExtensionResources.fr.xlf
  src/Platform/Microsoft.Testing.Extensions.VSTestBridge/Resources/xlf/ExtensionResources.it.xlf
  src/Platform/Microsoft.Testing.Extensions.VSTestBridge/Resources/xlf/ExtensionResources.ja.xlf
  src/Platform/Microsoft.Testing.Extensions.VSTestBridge/Resources/xlf/ExtensionResources.ko.xlf
  src/Platform/Microsoft.Testing.Extensions.VSTestBridge/Resources/xlf/ExtensionResources.pl.xlf
  src/Platform/Microsoft.Testing.Extensions.VSTestBridge/Resources/xlf/ExtensionResources.pt-BR.xlf
  src/Platform/Microsoft.Testing.Extensions.VSTestBridge/Resources/xlf/ExtensionResources.ru.xlf
  src/Platform/Microsoft.Testing.Extensions.VSTestBridge/Resources/xlf/ExtensionResources.tr.xlf
  src/Platform/Microsoft.Testing.Extensions.VSTestBridge/Resources/xlf/ExtensionResources.zh-Hans.xlf
  src/Platform/Microsoft.Testing.Extensions.VSTestBridge/Resources/xlf/ExtensionResources.zh-Hant.xlf
  test/UnitTests/Microsoft.Testing.Extensions.VSTestBridge.UnitTests/ObjectModel/ObjectModelConvertersTests.cs
Labels: Needs: Author Feedback

#3275 Fix collectionAssert.AreEqual fails for list of lists
  src/TestFramework/TestFramework/Assertions/CollectionAssert.cs
  test/UnitTests/TestFramework.UnitTests/Assertions/CollectionAssertTests.cs
Labels: Type: Bug, Area: Assertion

#3298 Feat: add support for overloaded parameterized tests
  src/Adapter/MSTest.TestAdapter/Discovery/TypeEnumerator.cs
  test/IntegrationTests/MSTest.IntegrationTests/Parameterized tests/DataRowTests.cs
  test/IntegrationTests/MSTest.IntegrationTests/Parameterized tests/DynamicDataTests.cs
  test/IntegrationTests/MSTest.VstestConsoleWrapper.IntegrationTests/Parameterized tests/DataRowTests.cs
  test/IntegrationTests/MSTest.VstestConsoleWrapper.IntegrationTests/Parameterized tests/DynamicDataTests.cs
  test/IntegrationTests/TestAssets/DataRowTestProject/DataRowTests_Regular.cs
  test/IntegrationTests/TestAssets/DynamicDataTestProject/DynamicDataTests.cs
Labels: Type: Feature, Area: Data Driven

#3331 Fix passing null to DataRow when signature is object[]
  src/Adapter/MSTest.TestAdapter/Extensions/MethodInfoExtensions.cs
  test/IntegrationTests/MSTest.IntegrationTests/Parameterized tests/DataRowTests.cs
  test/IntegrationTests/MSTest.VstestConsoleWrapper.IntegrationTests/Parameterized tests/DataRowTests.cs
  test/IntegrationTests/TestAssets/DataRowTestProject/DataRowTests_Regular.cs
Labels: Type: Bug

#3334 Fix: TestCleanup is always called in case of timeout
  src/Adapter/MSTest.TestAdapter/Execution/TestMethodInfo.cs
Labels: Type: Bug

#3339 Fix: Skip AssemblyInitialize/Cleanup when all tests are skipped
  src/Adapter/MSTest.TestAdapter/Execution/TestAssemblyInfo.cs
  src/Adapter/MSTest.TestAdapter/Execution/UnitTestRunner.cs
  test/IntegrationTests/MSTest.Acceptance.IntegrationTests/IgnoreTests.cs
Labels: Type: Bug

#3362 Fix class initialization/cleanup calls
  src/Adapter/MSTest.TestAdapter/Execution/TestClassInfo.cs
  src/Adapter/MSTest.TestAdapter/Execution/TypeCache.cs
  src/Adapter/MSTest.TestAdapter/Helpers/ReflectHelper.cs
  test/IntegrationTests/MSTest.VstestConsoleWrapper.IntegrationTests/SuiteLifeCycleTests.cs
  test/UnitTests/MSTestAdapter.UnitTests/Execution/TestClassInfoTests.cs
  test/UnitTests/MSTestAdapter.UnitTests/Execution/TypeCacheTests.cs
Labels: Type: Bug

#3374 MSTEST0018: DynamicData usage should be valid
  src/Adapter/MSTest.TestAdapter/Resources/Resource.Designer.cs
  src/Adapter/MSTest.TestAdapter/Resources/Resource.resx
  src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.cs.xlf
  src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.de.xlf
  src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.es.xlf
  src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.fr.xlf
  src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.it.xlf
  src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.ja.xlf
  src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.ko.xlf
  src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.pl.xlf
  src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.pt-BR.xlf
  src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.ru.xlf
  src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.tr.xlf
  src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.zh-Hans.xlf
  src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.zh-Hant.xlf
  src/Analyzers/MSTest.Analyzers/AnalyzerReleases.Unshipped.md
  src/Analyzers/MSTest.Analyzers/DynamicDataShouldBeValidAnalyzer.cs
  src/Analyzers/MSTest.Analyzers/Helpers/DiagnosticIds.cs
  src/Analyzers/MSTest.Analyzers/Helpers/WellKnownTypeNames.cs
  src/Analyzers/MSTest.Analyzers/PublicAPI.Unshipped.txt
  src/Analyzers/MSTest.Analyzers/Resources.Designer.cs
  src/Analyzers/MSTest.Analyzers/Resources.resx
  src/Analyzers/MSTest.Analyzers/RoslynAnalyzerHelpers/ISymbolExtensions.cs
  src/Analyzers/MSTest.Analyzers/xlf/Resources.cs.xlf
  src/Analyzers/MSTest.Analyzers/xlf/Resources.de.xlf
  src/Analyzers/MSTest.Analyzers/xlf/Resources.es.xlf
  src/Analyzers/MSTest.Analyzers/xlf/Resources.fr.xlf
  src/Analyzers/MSTest.Analyzers/xlf/Resources.it.xlf
  src/Analyzers/MSTest.Analyzers/xlf/Resources.ja.xlf
  src/Analyzers/MSTest.Analyzers/xlf/Resources.ko.xlf
  src/Analyzers/MSTest.Analyzers/xlf/Resources.pl.xlf
  src/Analyzers/MSTest.Analyzers/xlf/Resources.pt-BR.xlf
  src/Analyzers/MSTest.Analyzers/xlf/Resources.ru.xlf
  src/Analyzers/MSTest.Analyzers/xlf/Resources.tr.xlf
  src/Analyzers/MSTest.Analyzers/xlf/Resources.zh-Hans.xlf
  src/Analyzers/MSTest.Analyzers/xlf/Resources.zh-Hant.xlf
  test/UnitTests/MSTest.Analyzers.UnitTests/DynamicDataShouldBeValidAnalyzerTests.cs
Labels: Type: Feature, Area: Analyzers
