Repository microsoft/testfx, pull requests merged in 2024-04, with the labels that each got.

#2680 Cache `CommandLineOption` from the providers
  src/Platform/Microsoft.Testing.Platform/CommandLine/CommandLineManager.cs
  src/Platform/Microsoft.Testing.Platform/CommandLine/CommandLineOptionsProviderCache.cs
Labels: Area: Performance

#2690 Improve error message when dynamic data source layout is invalid
  src/TestFramework/TestFramework/Attributes/DataSource/DynamicDataAttribute.cs
  src/TestFramework/TestFramework/Resources/FrameworkMessages.Designer.cs
  src/TestFramework/TestFramework/Resources/FrameworkMessages.resx
  src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.cs.xlf
  src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.de.xlf
  src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.es.xlf
  src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.fr.xlf
  src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.it.xlf
  src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.ja.xlf
  src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.ko.xlf
  src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.pl.xlf
  src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.pt-BR.xlf
  src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.ru.xlf
  src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.tr.xlf
  src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.zh-Hans.xlf
  src/TestFramework/TestFramework/Resources/xlf/FrameworkMessages.zh-Hant.xlf
Labels: Type: Feature, Area: Data Driven

#2691 Improve error message for mismatched data driven test
  src/Adapter/MSTest.TestAdapter/Execution/TestMethodInfo.cs
  src/Adapter/MSTest.TestAdapter/Extensions/MethodInfoExtensions.cs
  src/Adapter/MSTest.TestAdapter/MSTest.TestAdapter.csproj
  src/Adapter/MSTest.TestAdapter/Resources/Resource.Designer.cs
  src/Adapter/MSTest.TestAdapter/Resources/Resource.resx
  src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.cs.xlf
  src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.de.xlf
  src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.es.xlf
  src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.fr.xlf
  src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.it.xlf
  src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.ja.xlf
  src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.ko.xlf
  src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.pl.xlf
  src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.pt-BR.xlf
  src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.ru.xlf
  src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.tr.xlf
  src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.zh-Hans.xlf
  src/Adapter/MSTest.TestAdapter/Resources/xlf/Resource.zh-Hant.xlf
  test/IntegrationTests/MSTest.IntegrationTests/Parameterized tests/DataRowTests.cs
  test/IntegrationTests/MSTest.VstestConsoleWrapper.IntegrationTests/Parameterized tests/DataRowTests.cs
  test/UnitTests/MSTestAdapter.UnitTests/Extensions/MethodInfoExtensionsTests.cs
  test/Utilities/Automation.CLI/CLITestBase.common.cs
  test/Utilities/Automation.CLI/RunConfiguration.cs
Labels: Type: Feature

#2747 perf: reduce allocations and calls to ToArray
  src/Adapter/MSTest.TestAdapter/Discovery/AssemblyEnumerator.cs
  src/Adapter/MSTest.TestAdapter/Discovery/TypeEnumerator.cs
  src/Adapter/MSTest.TestAdapter/Execution/TestExecutionManager.cs
  src/Adapter/MSTest.TestAdapter/Execution/TestMethodRunner.cs
  src/Adapter/MSTest.TestAdapter/Execution/TypeCache.cs
  src/Adapter/MSTest.TestAdapter/Execution/UnitTestRunner.cs
  src/Adapter/MSTest.TestAdapter/Extensions/TestResultExtensions.cs
  src/Adapter/MSTestAdapter.PlatformServices/Deployment/AssemblyLoadWorker.cs
  src/Adapter/MSTestAdapter.PlatformServices/Services/ReflectionOperations.cs
  src/Adapter/MSTestAdapter.PlatformServices/Services/TestSourceHost.cs
  src/Adapter/MSTestAdapter.PlatformServices/Utilities/AssemblyUtility.cs
  src/Adapter/MSTestAdapter.PlatformServices/Utilities/DeploymentItemUtility.cs
  src/Adapter/MSTestAdapter.PlatformServices/Utilities/DeploymentUtility.cs
  src/Adapter/MSTestAdapter.PlatformServices/Utilities/DeploymentUtilityBase.cs
  src/Adapter/MSTestAdapter.PlatformServices/Utilities/ReflectionUtility.cs
  test/IntegrationTests/PlatformServices.Desktop.IntegrationTests/ReflectionUtilityTests.cs
  test/UnitTests/MSTestAdapter.PlatformServices.UnitTests/Utilities/DesktopReflectionUtilityTests.cs
  test/UnitTests/MSTestAdapter.PlatformServices.UnitTests/Utilities/ns13DeploymentItemUtilityTests.cs
  test/UnitTests/MSTestAdapter.PlatformServices.UnitTests/Utilities/ns13ReflectionUtilityTests.cs
  test/UnitTests/MSTestAdapter.UnitTests/Discovery/AssemblyEnumeratorTests.cs
  test/UnitTests/MSTestAdapter.UnitTests/Execution/TypeCacheTests.cs
Labels: Area: Performance
