Repository microsoft/testfx, pull requests merged in 2024-06, with the labels that each got.

#3015 TestCaseFilter with custom properties
  src/Adapter/MSTest.TestAdapter/TestMethodFilter.cs
  test/IntegrationTests/MSTest.Acceptance.IntegrationTests/TestFilterTests.cs
  test/IntegrationTests/MSTest.Acceptance.IntegrationTests/testsbaseline.txt
Labels: Type: Feature

#3053 Improve display name when DataRow contains arrays
  src/Adapter/MSTest.TestAdapter/Discovery/AssemblyEnumerator.cs
  src/TestFramework/TestFramework/Attributes/DataSource/DataRowAttribute.cs
  src/TestFramework/TestFramework/PublicAPI/PublicAPI.Unshipped.txt
  test/IntegrationTests/MSTest.IntegrationTests/Parameterized tests/DataRowTests.cs
  test/IntegrationTests/MSTest.IntegrationTests/TestId.DefaultStrategy.cs
  test/IntegrationTests/MSTest.IntegrationTests/TestId.FullyQualifiedStrategy.cs
  test/IntegrationTests/MSTest.VstestConsoleWrapper.IntegrationTests/Parameterized tests/DataRowTests.cs
  test/UnitTests/TestFramework.UnitTests/Attributes/DataRowAttributeTests.cs
Labels: Type: Feature, Area: Data Driven

#3082 Improve display name for string and char
  src/TestFramework/TestFramework/Attributes/DataSource/DataRowAttribute.cs
  test/IntegrationTests/MSTest.IntegrationTests/ClsTests.cs
  test/IntegrationTests/MSTest.IntegrationTests/Parameterized tests/DataExtensibilityTests.cs
  test/IntegrationTests/MSTest.IntegrationTests/Parameterized tests/DataRowTests.cs
  test/IntegrationTests/MSTest.IntegrationTests/TestId.DefaultStrategy.cs
  test/IntegrationTests/MSTest.IntegrationTests/TestId.FullyQualifiedStrategy.cs
  test/IntegrationTests/MSTest.VstestConsoleWrapper.IntegrationTests/Parameterized tests/DataExtensibilityTests.cs
  test/IntegrationTests/MSTest.VstestConsoleWrapper.IntegrationTests/Parameterized tests/DataRowTests.cs
  test/UnitTests/MSTestAdapter.UnitTests/Execution/TestMethodRunnerTests.cs
  test/UnitTests/TestFramework.UnitTests/Attributes/DataRowAttributeTests.cs
Labels: Type: Feature, Area: Data Driven

#3106 MSTest runner: allow overriding TestRunParameters
  src/Adapter/MSTest.TestAdapter/TestingPlatformAdapter/TestApplicationBuilderExtensions.cs
  test/IntegrationTests/MSTest.Acceptance.IntegrationTests/TestRunParametersTests.cs
  test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/HelpTests.cs
  test/IntegrationTests/Microsoft.Testing.Platform.Acceptance.IntegrationTests/InfoTests.cs
Labels: Needs: Attention :wave:

#2904 Display fixture (Assembly/Class Initialize/Cleanup) methods as "test" entries
  TestFx.sln
  src/Adapter/MSTest.TestAdapter/Constants.cs
  src/Adapter/MSTest.TestAdapter/Discovery/AssemblyEnumerator.cs
  src/Adapter/MSTest.TestAdapter/Discovery/UnitTestDiscoverer.cs
  src/Adapter/MSTest.TestAdapter/Execution/TestAssemblyInfo.cs
  src/Adapter/MSTest.TestAdapter/Execution/TestExecutionManager.cs
  src/Adapter/MSTest.TestAdapter/Execution/UnitTestRunner.cs
  src/Adapter/MSTest.TestAdapter/MSTest.TestAdapter.csproj
  src/Adapter/MSTest.TestAdapter/MSTestSettings.cs
  src/Adapter/MSTest.TestAdapter/ObjectModel/FixtureTestResult.cs
  src/Adapter/MSTestAdapter.PlatformServices/Services/MSTestAdapterSettings.cs
  test/IntegrationTests/MSTest.VstestConsoleWrapper.IntegrationTests/FixturesTests.cs
  test/IntegrationTests/TestAssets/FixturesTestProject/FixturesTestProject.csproj
  test/IntegrationTests/TestAssets/FixturesTestProject/UnitTest1.cs
Labels: Type: Feature
