Repository microsoft/testfx, pull requests merged in 2025-06, with the labels that each got.

#5679 Enable filtering with `TestMetadataProperty` in the treenode filter
  src/Platform/Microsoft.Testing.Platform/Messages/TestNodeProperties.cs
  src/Platform/Microsoft.Testing.Platform/Requests/TreeNodeFilter/TreeNodeFilter.cs
  test/UnitTests/Microsoft.Testing.Platform.UnitTests/Messages/TestNodePropertiesTests.cs
  test/UnitTests/Microsoft.Testing.Platform.UnitTests/Requests/TreeNodeFilterTests.cs
Labels: Needs: Attention :wave:

#5832 Change IsInstanceOfType to return the instance of type T
  src/TestFramework/TestFramework/Assertions/Assert.IsInstanceOfType.cs
  test/UnitTests/TestFramework.UnitTests/Assertions/AssertTests.IsInstanceOfTypeTests.cs
  test/UnitTests/TestFramework.UnitTests/Assertions/AssertTests.ThrowsExceptionTests.cs
Labels: Breaking :bangbang:

#5829 Drop TestTimeout enum
  src/TestFramework/TestFramework/Attributes/TestMethod/TestTimeout.cs
  src/TestFramework/TestFramework/Attributes/TestMethod/TimeoutAttribute.cs
  test/IntegrationTests/TestAssets/TimeoutTestProject/TimeoutTestClass.cs
Labels: Breaking :bangbang:

#5834 Internalize obsolete types
  src/Adapter/MSTest.TestAdapter/MSTest.TestAdapter.csproj
  src/Adapter/MSTest.TestAdapter/VSTestAdapter/MSTestDiscoverer.cs
  src/Adapter/MSTest.TestAdapter/VSTestAdapter/MSTestExecutor.cs
  src/Adapter/MSTestAdapter.PlatformServices/AssemblyResolver.cs
  test/UnitTests/MSTestAdapter.PlatformServices.UnitTests/AssemblyResolverTests.cs
Labels: Breaking :bangbang:

#5837 Make TestMethodInfo internal
  src/Adapter/MSTestAdapter.PlatformServices/Execution/TestMethodInfo.cs
Labels: Breaking :bangbang:

#5833 Make ITestMethod internal
  src/Adapter/MSTestAdapter.PlatformServices/Interfaces/ObjectModel/ITestMethod.cs
  src/Adapter/MSTestAdapter.PlatformServices/ObjectModel/TestMethod.cs
  src/Adapter/MSTestAdapter.PlatformServices/Services/TestContextImplementation.cs
  test/UnitTests/MSTestAdapter.PlatformServices.UnitTests/Discovery/TypeEnumeratorTests.cs
Labels: Breaking :bangbang:

#5827 Remove ClassCleanupBehavior
  src/Adapter/MSTestAdapter.PlatformServices/Execution/ClassCleanupManager.cs
  src/Adapter/MSTestAdapter.PlatformServices/Execution/TestAssemblySettingsProvider.cs
  src/Adapter/MSTestAdapter.PlatformServices/Execution/TestClassInfo.cs
  src/Adapter/MSTestAdapter.PlatformServices/Execution/TestExecutionManager.cs
  src/Adapter/MSTestAdapter.PlatformServices/Execution/UnitTestRunner.cs
  src/Adapter/MSTestAdapter.PlatformServices/Helpers/ReflectHelper.cs
  src/Adapter/MSTestAdapter.PlatformServices/MSTestSettings.cs
  src/Adapter/MSTestAdapter.PlatformServices/ObjectModel/TestAssemblySettings.cs
  src/Analyzers/MSTest.Analyzers/Helpers/DiagnosticIds.cs
  src/Analyzers/MSTest.Analyzers/UseClassCleanupBehaviorEndOfClassAnalyzer.cs
  src/TestFramework/TestFramework/Attributes/Lifecycle/Cleanup/ClassCleanupAttribute.cs
  src/TestFramework/TestFramework/Attributes/Lifecycle/Cleanup/ClassCleanupBehavior.cs
  src/TestFramework/TestFramework/Attributes/Lifecycle/Cleanup/ClassCleanupExecutionAttribute.cs
  test/IntegrationTests/MSTest.Acceptance.IntegrationTests/InconclusiveTests.cs
  test/IntegrationTests/MSTest.Acceptance.IntegrationTests/STATestClassTests.cs
  test/IntegrationTests/MSTest.Acceptance.IntegrationTests/STATestMethodTests.cs
  test/IntegrationTests/MSTest.Acceptance.IntegrationTests/ThreadContextTests.cs
  test/IntegrationTests/MSTest.VstestConsoleWrapper.IntegrationTests/SuiteLifeCycleTests.cs
  test/IntegrationTests/TestAssets/OutputTestProject/Assembly.cs
  test/IntegrationTests/TestAssets/SuiteLifeCycleTestProject/LifeCycleClassCleanup.cs
  test/IntegrationTests/TestAssets/SuiteLifeCycleTestProject/LifeCycleClassCleanupEndOfAssembly.cs
  test/IntegrationTests/TestAssets/SuiteLifeCycleTestProject/LifeCycleClassCleanupEndOfAssemblyAndBeforeEachDerivedClass.cs
  test/IntegrationTests/TestAssets/SuiteLifeCycleTestProject/LifeCycleClassCleanupEndOfAssemblyAndNone.cs
  test/IntegrationTests/TestAssets/SuiteLifeCycleTestProject/LifeCycleClassCleanupEndOfClass.cs
  test/IntegrationTests/TestAssets/SuiteLifeCycleTestProject/LifeCycleClassCleanupEndOfClassAndBeforeEachDerivedClass.cs
  test/IntegrationTests/TestAssets/SuiteLifeCycleTestProject/LifeCycleClassCleanupEndOfClassAndNone.cs
  test/IntegrationTests/TestAssets/SuiteLifeCycleTestProject/LifeCycleDerivedClassCleanupEndOfAssemblyAndBeforeEachDerivedClass.cs
  test/IntegrationTests/TestAssets/SuiteLifeCycleTestProject/LifeCycleDerivedClassCleanupEndOfAssemblyAndNone.cs
  test/IntegrationTests/TestAssets/SuiteLifeCycleTestProject/LifecycleInheritance.cs
  test/UnitTests/MSTest.Analyzers.UnitTests/Program.cs
  test/UnitTests/MSTest.Analyzers.UnitTests/UseClassCleanupBehaviorEndOfClassAnalyzerTests.cs
  test/UnitTests/MSTestAdapter.PlatformServices.UnitTests/Execution/ClassCleanupManagerTests.cs
  test/UnitTests/MSTestAdapter.PlatformServices.UnitTests/Execution/UnitTestRunnerTests.cs
Labels: Breaking :bangbang:, Area: MSTest

#5846 Remove GenericParameterHelper
  src/TestFramework/TestFramework/GenericParameterHelper.cs
Labels: Breaking :bangbang:

#5841 Cleanup assertions
  src/TestFramework/TestFramework/Assertions/Assert.AreEqual.cs
  src/TestFramework/TestFramework/Assertions/Assert.AreSame.cs
  src/TestFramework/TestFramework/Assertions/Assert.Contains.cs
  src/TestFramework/TestFramework/Assertions/Assert.Count.cs
  src/TestFramework/TestFramework/Assertions/Assert.EndsWith.cs
  src/TestFramework/TestFramework/Assertions/Assert.Fail.cs
  src/TestFramework/TestFramework/Assertions/Assert.IComparable.cs
  src/TestFramework/TestFramework/Assertions/Assert.Inconclusive.cs
  src/TestFramework/TestFramework/Assertions/Assert.IsInstanceOfType.cs
  src/TestFramework/TestFramework/Assertions/Assert.IsNull.cs
  src/TestFramework/TestFramework/Assertions/Assert.IsTrue.cs
  src/TestFramework/TestFramework/Assertions/Assert.Matches.cs
  src/TestFramework/TestFramework/Assertions/Assert.StartsWith.cs
  src/TestFramework/TestFramework/Assertions/Assert.ThrowsException.cs
  src/TestFramework/TestFramework/Assertions/Assert.cs
  src/TestFramework/TestFramework/Assertions/CollectionAssert.cs
  src/TestFramework/TestFramework/Assertions/StringAssert.cs
  test/UnitTests/MSTest.Analyzers.UnitTests/AssertionArgsShouldBePassedInCorrectOrderAnalyzerTests.cs
  test/UnitTests/MSTest.Analyzers.UnitTests/AvoidAssertAreSameWithValueTypesAnalyzerTests.cs
  test/UnitTests/MSTest.Analyzers.UnitTests/PreferAssertFailOverAlwaysFalseConditionsAnalyzerTests.cs
  test/UnitTests/MSTest.Analyzers.UnitTests/UseNewerAssertThrowsAnalyzerTests.cs
  test/UnitTests/TestFramework.UnitTests/Assertions/AssertTests.AreSame.cs
  test/UnitTests/TestFramework.UnitTests/Assertions/AssertTests.Contains.cs
  test/UnitTests/TestFramework.UnitTests/Assertions/AssertTests.IComparableTests.cs
  test/UnitTests/TestFramework.UnitTests/Assertions/AssertTests.InconclusiveTests.cs
  test/UnitTests/TestFramework.UnitTests/Assertions/AssertTests.IsInRange.cs
  test/UnitTests/TestFramework.UnitTests/Assertions/AssertTests.IsInstanceOfTypeTests.cs
  test/UnitTests/TestFramework.UnitTests/Assertions/AssertTests.IsNull.cs
  test/UnitTests/TestFramework.UnitTests/Assertions/AssertTests.IsTrueTests.cs
  test/UnitTests/TestFramework.UnitTests/Assertions/AssertTests.Items.cs
  test/UnitTests/TestFramework.UnitTests/Assertions/AssertTests.ThrowsExceptionTests.cs
  test/UnitTests/TestFramework.UnitTests/Assertions/AssertTests.cs
  test/UnitTests/TestFramework.UnitTests/Assertions/CollectionAssertTests.cs
  test/UnitTests/TestFramework.UnitTests/Assertions/StringAssertTests.cs
Labels: Breaking :bangbang:

#5843 Rename assemblies and don't fix version to 14
  Directory.Build.targets
  src/Adapter/MSTest.TestAdapter/MSTest.TestAdapter.NonWindows.nuspec
  src/Adapter/MSTest.TestAdapter/MSTest.TestAdapter.csproj
  src/Adapter/MSTest.TestAdapter/MSTest.TestAdapter.nuspec
  src/Adapter/MSTest.TestAdapter/buildTransitive/common/MSTest.TestAdapter.targets
  src/Adapter/MSTest.TestAdapter/buildTransitive/uwp/MSTest.TestAdapter.targets
  src/Adapter/MSTestAdapter.PlatformServices/EngineConstants.cs
  src/Adapter/MSTestAdapter.PlatformServices/MSTestAdapter.PlatformServices.csproj
  src/Adapter/MSTestAdapter.PlatformServices/Services/TestSource.cs
  src/Analyzers/MSTest.Analyzers/UseParallelizeAttributeAnalyzer.cs
  src/Platform/Microsoft.Testing.Extensions.VSTestBridge/Helpers/Constants.cs
  src/TestFramework/TestFramework.Extensions/MSTest.TestFramework.NonWindows.nuspec
  src/TestFramework/TestFramework.Extensions/MSTest.TestFramework.nuspec
  src/TestFramework/TestFramework.Extensions/TestFramework.Extensions.csproj
  src/TestFramework/TestFramework.Extensions/buildTransitive/net6.0AndLater/MSTest.TestFramework.targets
  src/TestFramework/TestFramework/TestFramework.csproj
  test/IntegrationTests/MSTest.Acceptance.IntegrationTests/DataSourceTests.cs
  test/IntegrationTests/MSTest.Acceptance.IntegrationTests/SdkTests.cs
  test/UnitTests/MSTestAdapter.PlatformServices.UnitTests/MSTestAdapter.PlatformServices.UnitTests.csproj
  test/UnitTests/MSTestAdapter.PlatformServices.UnitTests/Utilities/XmlUtilitiesTests.cs
  test/UnitTests/MSTestAdapter.UnitTests/MSTestDiscovererTests.cs
  test/UnitTests/MSTestAdapter.UnitTests/MSTestExecutorTests.cs
Labels: Breaking :bangbang:

#5855 Remove TestIdGenerationStrategy
  TestFx.slnx
  src/Adapter/MSTestAdapter.PlatformServices/Discovery/AssemblyEnumerator.cs
  src/Adapter/MSTestAdapter.PlatformServices/Discovery/TypeEnumerator.cs
  src/Adapter/MSTestAdapter.PlatformServices/EngineConstants.cs
  src/Adapter/MSTestAdapter.PlatformServices/Execution/TestAssemblySettingsProvider.cs
  src/Adapter/MSTestAdapter.PlatformServices/Execution/TestMethodRunner.cs
  src/Adapter/MSTestAdapter.PlatformServices/Extensions/TestCaseExtensions.cs
  src/Adapter/MSTestAdapter.PlatformServices/Helpers/ReflectHelper.cs
  src/Adapter/MSTestAdapter.PlatformServices/Interfaces/ObjectModel/ITestMethod.cs
  src/Adapter/MSTestAdapter.PlatformServices/ObjectModel/TestMethod.cs
  src/Adapter/MSTestAdapter.PlatformServices/ObjectModel/UnitTestElement.cs
  src/TestFramework/TestFramework/Attributes/DataSource/DataRowAttribute.cs
  src/TestFramework/TestFramework/Attributes/DataSource/DynamicDataAttribute.cs
  src/TestFramework/TestFramework/Attributes/DataSource/TestIdGenerationStrategy.cs
  src/TestFramework/TestFramework/Attributes/DataSource/TestIdGenerationStrategyAttribute.cs
  src/TestFramework/TestFramework/Internal/TestDataSourceUtilities.cs
  test/IntegrationTests/MSTest.IntegrationTests/TestId.DisplayNameStrategy.cs
  test/IntegrationTests/MSTest.IntegrationTests/TestId.FullyQualifiedStrategy.cs
  test/IntegrationTests/MSTest.IntegrationTests/TestId.LegacyStrategy.cs
  test/IntegrationTests/TestAssets/TestIdProject.DefaultStrategy/TestIdCases.cs
  test/IntegrationTests/TestAssets/TestIdProject.DisplayNameStrategy/TestIdProject.DisplayNameStrategy.csproj
  test/IntegrationTests/TestAssets/TestIdProject.LegacyStrategy/TestIdProject.LegacyStrategy.csproj
  test/UnitTests/MSTestAdapter.PlatformServices.UnitTests/Discovery/AssemblyEnumeratorTests.cs
  test/UnitTests/MSTestAdapter.PlatformServices.UnitTests/Discovery/TypeEnumeratorTests.cs
  test/UnitTests/MSTestAdapter.PlatformServices.UnitTests/ObjectModel/UnitTestElementTests.cs
  test/UnitTests/TestFramework.UnitTests/Attributes/DataRowAttributeTests.cs
  test/UnitTests/TestFramework.UnitTests/Attributes/DynamicDataAttributeTests.cs
Labels: Breaking :bangbang:

#5862 TestCase.Id shouldn't include executor uri
  src/Adapter/MSTestAdapter.PlatformServices/ObjectModel/UnitTestElement.cs
Labels: Breaking :bangbang:

#5853 Cleanup how to get attributes
  src/Adapter/MSTestAdapter.PlatformServices/Discovery/AssemblyEnumerator.cs
  src/Adapter/MSTestAdapter.PlatformServices/Discovery/TestMethodValidator.cs
  src/Adapter/MSTestAdapter.PlatformServices/Discovery/TypeEnumerator.cs
  src/Adapter/MSTestAdapter.PlatformServices/Discovery/TypeValidator.cs
  src/Adapter/MSTestAdapter.PlatformServices/Execution/TestMethodInfo.cs
  src/Adapter/MSTestAdapter.PlatformServices/Execution/TestMethodRunner.cs
  src/Adapter/MSTestAdapter.PlatformServices/Execution/TypeCache.cs
  src/Adapter/MSTestAdapter.PlatformServices/Extensions/MethodInfoExtensions.cs
  src/Adapter/MSTestAdapter.PlatformServices/Helpers/AttributeHelpers.cs
  src/Adapter/MSTestAdapter.PlatformServices/Helpers/ReflectHelper.cs
  src/Adapter/MSTestAdapter.PlatformServices/Interfaces/IReflectionOperations.cs
  src/Adapter/MSTestAdapter.PlatformServices/Services/ReflectionOperations.cs
  src/Adapter/MSTestAdapter.PlatformServices/Services/TestDataSource.cs
  src/Adapter/MSTestAdapter.PlatformServices/Utilities/ReflectionUtility.cs
  src/TestFramework/TestFramework/Attributes/DataSource/DataRowAttribute.cs
  src/TestFramework/TestFramework/Attributes/DataSource/DataSourceAttribute.cs
  src/TestFramework/TestFramework/Attributes/DataSource/DynamicDataAttribute.cs
  src/TestFramework/TestFramework/Attributes/Lifecycle/Cleanup/AssemblyCleanupAttribute.cs
  src/TestFramework/TestFramework/Attributes/Lifecycle/Cleanup/ClassCleanupAttribute.cs
  src/TestFramework/TestFramework/Attributes/Lifecycle/Cleanup/TestCleanupAttribute.cs
  src/TestFramework/TestFramework/Attributes/Lifecycle/Initialization/AssemblyInitializeAttribute.cs
  src/TestFramework/TestFramework/Attributes/Lifecycle/Initialization/ClassInitializeAttribute.cs
  src/TestFramework/TestFramework/Attributes/Lifecycle/Initialization/TestInitializeAttribute.cs
  src/TestFramework/TestFramework/Attributes/TestMethod/TestMethodAttribute.cs
  src/TestFramework/TestFramework/Attributes/TestMethod/TimeoutAttribute.cs
  src/TestFramework/TestFramework/Interfaces/ITestMethod.cs
  test/IntegrationTests/PlatformServices.Desktop.IntegrationTests/ReflectionUtilityTests.cs
  test/UnitTests/MSTestAdapter.PlatformServices.UnitTests/Discovery/TestMethodValidatorTests.cs
  test/UnitTests/MSTestAdapter.PlatformServices.UnitTests/Discovery/TypeValidatorTests.cs
  test/UnitTests/MSTestAdapter.PlatformServices.UnitTests/Execution/TestExecutionManagerTests.cs
  test/UnitTests/MSTestAdapter.PlatformServices.UnitTests/Execution/TestMethodRunnerTests.cs
  test/UnitTests/MSTestAdapter.PlatformServices.UnitTests/Execution/TypeCacheTests.cs
  test/UnitTests/MSTestAdapter.PlatformServices.UnitTests/Execution/UnitTestRunnerTests.cs
  test/UnitTests/MSTestAdapter.PlatformServices.UnitTests/Helpers/ReflectHelperTests.cs
  test/UnitTests/MSTestAdapter.PlatformServices.UnitTests/Services/DesktopReflectionOperationsTests.cs
  test/UnitTests/MSTestAdapter.PlatformServices.UnitTests/Services/DesktopTestDataSourceTests.cs
  test/UnitTests/MSTestAdapter.PlatformServices.UnitTests/Services/ReflectionOperationsTests.cs
  test/UnitTests/MSTestAdapter.PlatformServices.UnitTests/Utilities/ns13ReflectionUtilityTests.cs
Labels: Breaking :bangbang:

#5867 Remove old Assert.ThrowsException APIs
  src/Analyzers/MSTest.Analyzers.CodeFixes/UseNewerAssertThrowsFixer.cs
  src/Analyzers/MSTest.Analyzers/UseNewerAssertThrowsAnalyzer.cs
  src/TestFramework/TestFramework/Assertions/Assert.ThrowsException.cs
  test/UnitTests/MSTest.Analyzers.UnitTests/UseNewerAssertThrowsAnalyzerTests.cs
  test/UnitTests/MSTest.Engine.UnitTests/DynamicDataNameProviderTests.cs
  test/UnitTests/MSTestAdapter.PlatformServices.UnitTests/Execution/TestMethodInfoTests.cs
  test/UnitTests/Microsoft.Testing.Extensions.VSTestBridge.UnitTests/ObjectModel/ObjectModelConvertersTests.cs
  test/UnitTests/Microsoft.Testing.Platform.UnitTests/Configuration/ConfigurationExtensionsTests.cs
  test/UnitTests/Microsoft.Testing.Platform.UnitTests/IPC/IPCTests.cs
  test/UnitTests/Microsoft.Testing.Platform.UnitTests/Logging/FileLoggerTests.cs
  test/UnitTests/Microsoft.Testing.Platform.UnitTests/Messages/PropertyBagTests.cs
  test/UnitTests/Microsoft.Testing.Platform.UnitTests/Messages/TestNodeUidTests.cs
  test/UnitTests/Microsoft.Testing.Platform.UnitTests/Requests/TreeNodeFilterTests.cs
  test/UnitTests/Microsoft.Testing.Platform.UnitTests/Services/ServiceProviderTests.cs
  test/UnitTests/Microsoft.Testing.Platform.UnitTests/TestApplicationBuilderTests.cs
  test/UnitTests/TestFramework.UnitTests/Assertions/AssertTests.ThrowsExceptionTests.cs
Labels: Breaking :bangbang:

#5864 Bump AvoidExpectedExceptionAttributeAnalyzer to warning
  src/Analyzers/MSTest.Analyzers/AnalyzerReleases.Unshipped.md
  src/Analyzers/MSTest.Analyzers/AvoidExpectedExceptionAttributeAnalyzer.cs
Labels: Area: Analyzers

#5863 Bump UseNewerAssertThrowsAnalyzer to warning
  src/Analyzers/MSTest.Analyzers/AnalyzerReleases.Unshipped.md
  src/Analyzers/MSTest.Analyzers/UseNewerAssertThrowsAnalyzer.cs
Labels: Area: Analyzers

#5871 Adjust TestCase.Id to account for randomized tests (include test case index instead of serialized data)
  src/Adapter/MSTestAdapter.PlatformServices/Discovery/AssemblyEnumerator.cs
  src/Adapter/MSTestAdapter.PlatformServices/EngineConstants.cs
  src/Adapter/MSTestAdapter.PlatformServices/Extensions/TestCaseExtensions.cs
  src/Adapter/MSTestAdapter.PlatformServices/ObjectModel/TestMethod.cs
  src/Adapter/MSTestAdapter.PlatformServices/ObjectModel/UnitTestElement.cs
  test/UnitTests/MSTestAdapter.PlatformServices.UnitTests/ObjectModel/UnitTestElementTests.cs
Labels: Breaking :bangbang:

#5879 Make UseCooperativeCancellationForTimeoutAnalyzer warning
  src/Analyzers/MSTest.Analyzers/AnalyzerReleases.Unshipped.md
  src/Analyzers/MSTest.Analyzers/UseCooperativeCancellationForTimeoutAnalyzer.cs
Labels: Breaking :bangbang:

#5875 Default TreatDiscoveryWarningsAsErrors to true
  src/Adapter/MSTestAdapter.PlatformServices/MSTestSettings.cs
  test/UnitTests/MSTestAdapter.PlatformServices.UnitTests/Discovery/UnitTestDiscovererTests.cs
  test/UnitTests/MSTestAdapter.PlatformServices.UnitTests/MSTestSettingsTests.cs
Labels: Breaking :bangbang:

#5881 TestContext cleanup
  src/Adapter/MSTestAdapter.PlatformServices/Execution/ClassCleanupManager.cs
  src/Adapter/MSTestAdapter.PlatformServices/Execution/UnitTestRunner.cs
  src/Adapter/MSTestAdapter.PlatformServices/IPlatformServiceProvider.cs
  src/Adapter/MSTestAdapter.PlatformServices/PlatformServiceProvider.cs
  src/Adapter/MSTestAdapter.PlatformServices/Services/TestContextImplementation.cs
  src/TestFramework/TestFramework.Extensions/TestContext.cs
  test/IntegrationTests/MSTest.Acceptance.IntegrationTests/ThreadContextTests.cs
  test/UnitTests/MSTestAdapter.PlatformServices.UnitTests/Execution/TestAssemblyInfoTests.cs
  test/UnitTests/MSTestAdapter.PlatformServices.UnitTests/Execution/TestClassInfoTests.cs
  test/UnitTests/MSTestAdapter.PlatformServices.UnitTests/Execution/TestMethodInfoTests.cs
  test/UnitTests/MSTestAdapter.PlatformServices.UnitTests/Execution/TestMethodRunnerTests.cs
  test/UnitTests/MSTestAdapter.PlatformServices.UnitTests/Execution/TestPropertyAttributeTests.cs
  test/UnitTests/MSTestAdapter.PlatformServices.UnitTests/Execution/TypeCacheTests.cs
  test/UnitTests/MSTestAdapter.PlatformServices.UnitTests/PlatformServiceProviderTests.cs
  test/UnitTests/MSTestAdapter.PlatformServices.UnitTests/Services/TestContextImplementationTests.cs
  test/UnitTests/MSTestAdapter.PlatformServices.UnitTests/TestableImplementations/TestablePlatformServiceProvider.cs
Labels: Breaking :bangbang:
